### ISSUE TITLE
Batch Jobs Section

### ISSUE THREAD

**Issue by kkrick-sdsu** [csu-tide/csu-tide.github.io#12]
Add documentation to Batch Jobs/Common Tasks and Troubleshooting:
- Targeting TIDE Hardware (labels and tolerations; could link to example recipes - pod, job)

**Comment by joaquin-mendoza8** [comment]
index.md typo: (ln. 65) "wll" -> "will"

**Comment by joaquin-mendoza8** [comment]
`getting_access.md` link targets: attach `{:target="_blank"}` to links so they open up in new tabs (better UX)

**Comment by joaquin-mendoza8** [comment]
`getting_started.md` calls kubectl command with `$ns` but doesn't explain how to set that variable. Users will get errors when trying to use this command if they don't know this syntax

`kubectl -n $ns cp hello-pod:/usr/src/app/hello.txt ./hello.txt`

**Comment by kkrick-sdsu** [comment]
Done.
